### ISSUE TITLE
Comparison with other models in paper

### ISSUE THREAD

**Issue by bastorer** [pnsaevik/effluent#25]
In `Statement of need`, please expand a little bit on if the underlying model methods and features are different compared with `Effluent`. That would align well with the `State of the Field` requirement from JOSS. That `Effluent` is open-source is great, but some discussion of the differences in functionality versus CORMIX, VISUAL PLUMES, and VISJET would be helpful.

[ This is part of the JOSS review: https://github.com/openjournals/joss-reviews/issues/5554 ]

**Comment by pnsaevik** [comment]
Can you have a look at pull request #34 and see if it is sufficient? I don't think a detailed comparison is warranted here (after all, it's done in a published paper already..), but I've added a few key highlights.

**Comment by bastorer** [comment]
@pnsaevik the new citation and extra description are nice additions. Let me know when you merge #34 , I'll give the pdf one last look-over, but otherwise feel free to close this issue with PR #34

**Comment by pnsaevik** [comment]
Great. The PR is now merged.
