### ISSUE TITLE
Community guidelines

### ISSUE THREAD

**Issue by castelao** [pnsaevik/effluent#32]
Hi @pnsaevik , I hope you had a good summer break. I couldn't find the 'Community guidelines', which is a requirement for JOSS.

```
Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
```

[This is in reference to JOSS review https://github.com/https://github.com/openjournals/joss-reviews/issues/5554]

**Comment by pnsaevik** [comment]
I've now added a very brief (but hopefully sufficient) statement in #33. I don't think there is need for anything more verbose, do you agree?
