### ISSUE TITLE
Figure

### ISSUE THREAD

**Issue by castelao** [pnsaevik/effluent#40]
@pnsaevik , feel free to ignore this one.

You already have some nice figures in the documentation. Would it be worth adding any to the JOSS document? I appreciate the fact that JOSS focuses on the software documentation, which everyone will actually use, instead of the paper itself. But I feel that not all of our community is ready for that idea of 'go look the documentation'. It is perfectly fine as it is, I'm thinking about how could you attract more users for `effluent`. How to attract the curiosity of someone not used to software/data papers that finds your JOSS paper?

You can just close this issue if you have a different opinion.

**Comment by pnsaevik** [comment]
I like the idea of JOSS, that the online documentation "is" the paper, and am a bit hesitant to "bloating" the paper.md too much. But a single figure is fine, for the reasons you mention. It's added in #43.
